import { spawn } from 'node:child_process';
import { createServer } from 'vite';
import { build } from 'esbuild';
import electron from 'electron';
await build({ entryPoints: ['src/main/main.ts'], outfile: 'dist/main.cjs', platform: 'node', format: 'cjs', bundle: true, external: ['electron', 'playwright-core', 'exceljs'], sourcemap: true });
await build({ entryPoints: ['src/main/preload.ts'], outfile: 'dist/preload.cjs', platform: 'node', format: 'cjs', bundle: true, external: ['electron'] });
const server = await createServer(); await server.listen();
const child = spawn(electron, ['.'], { stdio: 'inherit', env: { ...process.env, DOM_DEV_URL: 'http://127.0.0.1:5173' } });
const stop = async () => { child.kill(); await server.close(); };
child.on('exit', async code => { await server.close(); process.exitCode = code ?? 1; });
process.on('SIGINT', stop); process.on('SIGTERM', stop);
